### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#34]
- [ ] The Number 3 feature is exporting a source-format font into a binary OTF (only)

**Comment by davelab6** [comment]
Let's start with OTF only for now

**Comment by YashAgarwal** [comment]
Having some errors with this
I've tried multiple ufo files but with some defcon doesn't show an error but ufo2ft does or vice versa

```
Error: defcon.errors.DefconError: the kerning data is not valid
```

Here is the code:
loading the font

``` python
 self.main_path = "ufo/sample.ufo"
 self.main_font = Font(self.main_path)        
```

the export function

``` python
def _write_ttf(self, button):
        ##NOT WORKING##
        ##Error: defcon.errors.DefconError: the kerning data is not valid##

        file_name = os.path.join(self.get_activity_root(), 'instance',
                                 '%s.ttf' % self.metadata['title'])

        #file_name = self.metadata['title'] + '.ttf' 

        ttf = compileTTF(self.main_font)
        ttf.save(file_name)

        jobject = datastore.create()
        jobject.metadata['icon-color'] = profile.get_color().to_string()
        jobject.metadata['mime_type'] = 'application/ttf'

        jobject.metadata['title'] = self.metadata['title']
        jobject.file_path = file_name

        # jobject.metadata['preview'] = \
        #    self._get_preview_image(file_name)

        datastore.write(jobject, transfer_ownership=True)
        self._object_id = jobject.object_id

        self._show_journal_alert(_('Success'),
                                 _('A TTF Font file was created in the Journal'))
```

**Comment by davelab6** [comment]
```
    jobject.metadata['mime_type'] = 'application/ttf'
```

I suggest NOT doing TTFs, only OTFs.

**Comment by YashAgarwal** [comment]
the commands are same for both of them, so its the same thing

**Comment by davelab6** [comment]
Can you successfully export both kinds? :)

**Comment by YashAgarwal** [comment]
Yes, I can 
(but only outside sugar for now)
here is the code snippet for doing that

``` python
from ufo2ft import compileOTF, compileTTF
from defcon import Font

ufo = Font('abc.ufo')
otf = compileOTF(ufo)
ttf = compileTTF(ufo)
ttf.save('MyFont-Regular.ttf')
otf.save('MyFont-Regular.otf')
```

**Comment by davelab6** [comment]
If the only problem is with kerning, then we can just ignore kerning for the 1.0 release

**Comment by davelab6** [comment]
> here is the code snippet for doing that

I recommend using fontmake itself; your example misses steps like 

https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/font_project.py#L129-L135

**Comment by davelab6** [comment]
I believe the next step is to confirm this works in the upcoming .xo release

**Comment by YashAgarwal** [comment]
I'm getting the following error "can't find module compreffor" when using the module ufo2ft
[this](https://github.com/googlei18n/compreffor) is the git repo for this module but I don't know how I should include this in my sugar activity as it requires a ./setup.py install

**Comment by YashAgarwal** [comment]
ah, I figured out how to add the compreffor module but now I'm getting an error in it

```
  File "/home/broot/sugar-build/activities/edit-fonts-activity/EditFonts.py", line 443, in _export_otf
    otf = compileOTF(globals.FONT)
  File "third_party/ufo2ft/__init__.py", line 31, in compileOTF
    otf = postProcessor.process(useProductionNames, optimizeCff)
  File "third_party/ufo2ft/otfPostProcessor.py", line 25, in process
    comp.compress()
  File "third_party/compreffor/__init__.py", line 115, in compress
    self.run_executable()
  File "third_party/compreffor/__init__.py", line 135, in run_executable
    cxxCompressor.compreff(self.font, use_lib=False, **self.options)
  File "third_party/compreffor/cxxCompressor.py", line 248, in compreff
    subrs, glyph_encodings = read_data(td, results)
  File "third_party/compreffor/cxxCompressor.py", line 127, in read_data
    num_subrs = struct.unpack_from('<I', results[:4])[0]
struct.error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by davelab6** [comment]
I suggest reporting the bug upstream

**Comment by YashAgarwal** [comment]
the previous error was due to the **ufo2ft** module
Now I'm trying to use fontmake, It works fine on my system but in sugar it requires a dependency which I don't know how to add
this is the error I'm getting

```
bash-4.2$ python -m fontmake -u ../test_fonts/sample.ufo
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/broot/sugar-build/activities/edit-fonts-activity/third_party/fontmake/__main__.py", line 17, in <module>
    from fontmake.font_project import FontProject
  File "fontmake/font_project.py", line 25, in <module>
    from booleanOperations import BooleanOperationManager
  File "booleanOperations/__init__.py", line 2, in <module>
    from .booleanOperationManager import BooleanOperationManager
  File "booleanOperations/booleanOperationManager.py", line 3, in <module>
    from . import pyClipper
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by booleanOperations/pyClipper.so)
```

**Comment by YashAgarwal** [comment]
Can anyone help with the above error?

**Comment by davelab6** [comment]
The problem is that the `booleanOperations/pyClipper.so` is compiled and linked against a different copy of the C runtime `/lib64/libstdc++.so.6`

You can try installing the https://pypi.python.org/pypi/pyclipper package and using that instead of the .so file included in the git repo

**Comment by YashAgarwal** [comment]
yesterday in IM @davelab6  suggested to use the selective functions out of FontProject to avoid pyclipper by avoiding booleanOperations completely
but on running

``` python
import fontmake.font_project import FontProject
```

in a python interpreter in the terminal activity inside sugar importing booleanOperation can not be avoided and hence we get the same GLIBXX not found error

If I comment out the booleanOperations import statement in the font_project still there are other modules like compreffor which  require the same GLIBXX and hence we get the same error

I think if we can somehow add the fontmake's setup.py file to the activities setup.py so that it is compiled with the activity itself

**Comment by YashAgarwal** [comment]
@walterbender can you have a look at this
running

``` python
import fontmake.font_project import FontProject
```

still gives the error 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fontmake/font_project.py", line 25, in <module>
    from booleanOperations import BooleanOperationManager
  File "booleanOperations/__init__.py", line 2, in <module>
    from .booleanOperationManager import BooleanOperationManager
  File "booleanOperations/booleanOperationManager.py", line 3, in <module>
    from . import pyClipper
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by booleanOperations/pyClipper.so)
```

I've tried copying the way using in the Physics activity but that doesn't even get called because here the  `booleanOperations/booleanOperationManager.py` file directly includes the `pyClipper.so`

then I tried importing the ``libstdc++.so` file  before importing fontmake, 

``` python
from ctypes import cdll
from sys import path
path.insert(0, 'third_party/pyclipper/pyclipper_64')
libstdc = cdll.LoadLibrary("third_party/pyclipper/pyclipper_64/libstdc++.so")
libstdc = cdll.LoadLibrary("third_party/pyclipper/pyclipper_64/libstdc++.so.6")
```

but then I get the error on this line 

```
libstdc = cdll.LoadLibrary("third_party/pyclipper/pyclipper_64/libstdc++.so")
```

saying(roughly)

```
OSError: File or directory doesn't exist      
```

but I can see the file in the directory mentioned

PS: all this was tried in a sugar dev env on my 64bit Ubuntu 16.04 using the terminal activity

**Comment by davelab6** [comment]
@YashAgarwal I suggest looking again at avoiding booleanOperations. With only a few days left, I would prefer to have a .xo that can export fonts with overlaps.
