### ISSUE TITLE
Errors when running `python EditFonts.py`

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#55]
- [x] How to start the Activity from the source tree? :) 

``` py
# boot Fedora-Live-SoaS-x86_64-23-10.iso
$ sudo dnf install git -y;
$ git clone https://github.com/sugarlabs/edit-fonts-activity.git;
$ cd edit-fonts-activity;
# note this is silly, don't do this:
$ python EditFonts.py;
EditFonts.py:24: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf
```
- [x] This seem easy to fix :) 

``` python
EditFonts.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```
- [x] This seem easy to fix too :) 

``` python
/usr/lib/python2.7/site-packages/sugar3/graphics/icon.py:34: PyGIWarning: Rsvg was imported without specifying a version first. Use gi.require_version('Rsvg', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Rsvg
```
- [x] This is a bug upstream, already fixed (https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/aea65408f06ec930696b14bc9c2c452ceaaf6853)

``` python
/usr/lib/python2.7/site-packages/sugar3/graphics/window.py:26: PyGIWarning: GdkX11 was imported without specifying a version first. Use gi.require_version('GdkX11', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkX11
```
- [x] This is a bug upstream, I filed issue https://bugs.sugarlabs.org/ticket/4965

``` python
Traceback (most recent call last):
  File "EditFonts.py", line 38, in <module>
    from sugar3.activity import activity
  File "/usr/lib/python2.7/site-packages/sugar3/activity/activity.py", line 84, in <module>
    from sugar3.datastore import datastore
  File "/usr/lib/python2.7/site-packages/sugar3/datastore/datastore.py", line 75, in <module>
    _get_data_store()
  File "/usr/lib/python2.7/site-packages/sugar3/datastore/datastore.py", line 51, in _get_data_store
    _data_store.connect_to_signal('Created', __datastore_created_cb)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 544, in connect_to_signal
    dbus_interface, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 369, in connect_to_signal
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 148, in add_signal_receiver
    path, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 400, in add_signal_receiver
    self._require_main_loop()
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
$
```
- [x] This seems to be a problem caused by invoking the file directly (`python EditFonts.py`) rather than launching the activity from the Home screen.

**Comment by davelab6** [comment]
> How to start the Activity from the source tree? :)

Okay, seems I have to run `./setup.py dev` then go to the Home screen, list view, and run Edit Fonts. But this just refuses to work. @samdroid-apps is this the only way to start an activity? 

When I run `./setup.py install` I get this error about fontmake:

<img width="1166" alt="screen shot 2016-07-06 at 23 10 38" src="https://cloud.githubusercontent.com/assets/261579/16641477/e4809466-43ce-11e6-9357-26f29fba5999.png">

**Comment by YashAgarwal** [comment]
@davelab6 are you able to run it now?

**Comment by davelab6** [comment]
No; `python setup.py install` has the same error and when i run it after `python setup.py dev` I see this

<img width="536" alt="screen shot 2016-07-07 at 07 36 13" src="https://cloud.githubusercontent.com/assets/261579/16651996/84dba45a-4415-11e6-9fe5-fa3e1589a383.png">

**Comment by davelab6** [comment]
@YashAgarwal To reproduce, grab https://archive.fedoraproject.org/pub/fedora/linux/releases/23/Live/x86_64/Fedora-Live-SoaS-x86_64-23-10.iso and boot it in VirtualBox or similar and run:

```
sudo dnf install git -y;
git clone http://https://github.com/sugarlabs/edit-fonts-activity.git;
cd edit-fonts-activity;
python setup.py dev;
```

**Comment by davelab6** [comment]
The .xo activity bundle now runs :)
